name: Publish to crates.io
on:
  push:
    tags: [
      'byte_utils-v*',
      'crypto-rand-v*',
    ]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: Extract Crate Name
        run: |
          # Get the tag name and parse the crate name
          TAG_NAME="${GITHUB_REF##*/}"
          CRATE_NAME="${TAG_NAME#*-v}"
          echo $CRATE_NAME
          echo "CRATE_NAME=${CRATE_NAME}" >> $GITHUB_ENV

      - name: Publish
        working-directory: ${{ env.CRATE_NAME }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: cargo publish
